Fixed init command to use CHANGELOG.md by default (issue #2)

diff --git a/chag b/chag
--- a/chag
+++ b/chag
@@ -440,8 +440,8 @@ done
 
 if [ -z "$FILENAME" ]; then
   FILENAME=`pwd`"/CHANGELOG.md"
-  ([ -f "$FILENAME" ] || [ $COMMAND == "create" ]) || FILENAME=`pwd`"/CHANGELOG"
+  ([ -f "$FILENAME" ] || [ $COMMAND == "init" ] || [ $COMMAND == "create" ]) || FILENAME=`pwd`"/CHANGELOG"
 fi
-([ -f "$FILENAME" ] || [ $COMMAND == "create" ]) || die "File not found: $FILENAME"
+([ -f "$FILENAME" ] || [ $COMMAND == "init" ] || [ $COMMAND == "create" ]) || die "File not found: $FILENAME"
 
 $COMMAND $opt $@
